project_name: airlock
builds:
  - binary: airlock
    main: ./cmd/airlock/main.go
    goos:
      - linux
      - windows
      - darwin
snapshot:
  name_template: "{{ .Tag }}-next"
git:
  short_hash: true
dockers:
  - image: kamaln7/airlock
    binary: airlock
    dockerfile: Dockerfile-goreleaser
    tag_templates:
      - "{{ .Version }}"
      - latest
brew:
  github:
    owner: kamaln7
    name: airlock-tap
  folder: Formula
  caveats: "example config file at https://github.com/kamaln7/airlock/blob/master/config/example.yaml - place at ~/.airlock.yaml"
  description: "instantly deploy static websites and files to DigitalOcean spaces. usage: airlock <directory or file>"
  homepage: "https://airlock.space"
